export const productsData = [
  {
    id: 1,
    name: 'Chair',
    price: 39,
    condition: 'new',
    description: 'Black chair',
    colors: ['red', 'green', 'blue'],
    image: 'chair.jpg',
  },
  {
    id: 2,
    name: 'Lamp',
    price: 319,
    condition: 'used',
    description: 'Amazing lamp',
    colors: ['green', 'blue'],
    image: 'lamp.jpg',
  },
  {
    id: 3,
    name: 'Statue',
    price: 239,
    condition: 'used',
    description: 'Used Statue',
    colors: ['red'],
    image: 'tower.jpg',
  },
  {
    id: 4,
    name: 'Seat',
    price: 239,
    condition: 'new',
    description: 'Large Seat',
    colors: ['blue'],
    image: 'lounge.jpg',
  },
];
